version: '3'
services:
  #api1:
  # build:
  #    context: ./random_1
 #     dockerfile: Dockerfile
#   ports: 
#     - "8001:8000"
#   networks:
#     - my_network
#
# api2:
#   build:
#     context: ./random_2
#     dockerfile: Dockerfile
#   ports: 
#   - "8002:8000"
#   networks:
#   - my_network

  #  auth:
   # build:
    #  context: ./auth
     # dockerfile: Dockerfile
#    ports:
 #     - "8000:8000"
#
#   networks:
 #     - my_network


  contribute:
    build:
      context: ./contribute
      dockerfile: Dockerfile

    ports:
      - "8001:8000"
    networks:
      - my_network

  data:
    build:
      context: ./data
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    networks:
        - my_network

  generator:
    build:
      context: ./generator
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    networks:
      - my_network

  maps: 
    build:
      context: ./maps
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    networks:
      - my_network
  

  traitement:
    build:
      context: ./traitement
      dockerfile: Dockerfile
    ports:
      - "8006:8000"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - auth
      - contribute
      - data
      - generator
      - maps
      - traitement
    networks:
      - my_network


networks:
  my_network:
