name: Cleanup Azure - branch deletion

on:
  delete

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Delete Azure Container Instance
      run: |
        CONTAINER_GROUP="callforcode-${{ github.event.ref }}"
        az container delete --resource-group RG-CALL_FOR_CODE-MARCH --name $CONTAINER_GROUP --yes
