name: Deploy to Azure

on:
    push:
        branches:
            - '*'

permissions:
    id-token: write
    contents: read

env:
    RESOURCE_GROUP: RG-CALL_FOR_CODE-MARCH
    LOCATION: francecentral
    CONTAINER_GROUP: callforcode-${{ github.ref_name }}
    IMAGE_NAME: ${{ secrets.AZURE_ACR_SERVER }}/myapp:${{ github.sha }}
    ACI_DNS_LABEL: callforcode-${{ github.ref_name}}

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Login to Azure with SP
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Login to Azure Container Registry (ACR)
              run: |
                echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login ${{ secrets.AZURE_ACR_SERVER }} -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin
          

            - name: Build and push Docker image
              run: |
                echo "Building API service from API/docker-compose.yml"
                docker compose -f API/docker-compose.yml build
                docker images
                IMAGE_ID=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "api-" | head -n 1)
                echo "Tagging image $IMAGE_ID as ${{ env.IMAGE_NAME }}"
                docker tag $IMAGE_ID ${{ env.IMAGE_NAME }}
                echo "Pushing image ${{ env.IMAGE_NAME }}"
                docker push ${{ env.IMAGE_NAME }}

            - name: Delete existing container (if exists)
              run: |
                az container delete --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CONTAINER_GROUP }} --yes || true
              

            - name: Deploy to Azure Container Instances (ACI)
              run: |
                az container create --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CONTAINER_GROUP }} --image ${{ env.IMAGE_NAME }} --dns-name-label ${{ env.ACI_DNS_LABEL }} --ports 8000 --os-type Linux --cpu 1 --memory 1.5 --registry-login-server ${{ secrets.AZURE_ACR_SERVER }} --registry-username ${{ secrets.AZURE_ACR_USERNAME }} --registry-password ${{ secrets.AZURE_ACR_PASSWORD }}

            - name: Verify deployment
              run: |
                STATUS=$(az container show --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CONTAINER_GROUP }} --query "instanceView.state" -o tsv)
                if [[ "$STATUS" != "Running" ]]; then
                    echo "Deployment failed! Check Azure logs."
                    exit 1
                fi
                az container list --resource-group RG-CALL_FOR_CODE-MARCH --query "[].{Name:name, Status:instanceView.state}" --output table
